### ISSUE TITLE
How to add frontmatter block to my draft if the first line needs to be a title?

### ISSUE THREAD

**Issue by Anirog** [JoshuaOliphant/Drafts-to-Jekyll#1]
Hi, thanks for this script, do you know a way to add a frontmatter block to my draft? Because frontmatter must be the first thing in the file and the script requires the first line should be the title.

Thanks.

**Comment by JoshuaOliphant** [comment]
I just committed an update that creates frontmatter and uses the draft tags to create categories. If that isn't what you wanted, let me know, and I'm happy to update it again.

**Comment by Anirog** [comment]
This is exactly what I wanted, thank you.
